"use client";

import Link from "next/link";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import {
  CheckCircle2Icon,
  AlertTriangleIcon,
  AlertCircleIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SparklesIcon,
  ArrowRightIcon,
  RotateCcwIcon,
  LayoutDashboardIcon,
  InfoIcon,
  ListCheckIcon,
  StethoscopeIcon,
} from "lucide-react";

export interface AssessmentResultData {
  id?: string;
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | string;
  riskScore: number;
  riskFactors: string[];
  recommendations: string[];
  warningSigns: string[];
  nextStep: string;
  disclaimer: string;
  createdAt?: string;
}

interface AssessmentResultProps {
  result: AssessmentResultData;
  onReset: () => void;
}

export default function AssessmentResult({
  result,
  onReset,
}: AssessmentResultProps) {
  if (!result) return null;

  const normalizedLevel = (result.riskLevel || "LOW").toUpperCase();
  const safeScore = Math.max(0, Math.min(100, result.riskScore ?? 0));

  // Determine Risk Theme & Badging
  const getRiskConfig = (level: string) => {
    switch (level) {
      case "LOW":
        return {
          badgeText: "LOW RISK",
          badgeVariant: "default" as const,
          containerBg:
            "bg-emerald-500/10 border-emerald-500/30 text-emerald-700 dark:text-emerald-300",
          progressColor: "bg-emerald-500",
          icon: (
            <ShieldCheckIcon className="w-8 h-8 text-emerald-500 shrink-0" />
          ),
          subtitle:
            "Reassuring indicator based on your reported oral hygiene habits.",
        };
      case "MEDIUM":
        return {
          badgeText: "MEDIUM RISK",
          badgeVariant: "secondary" as const,
          containerBg:
            "bg-amber-500/10 border-amber-500/30 text-amber-800 dark:text-amber-300",
          progressColor: "bg-amber-500",
          icon: (
            <AlertTriangleIcon className="w-8 h-8 text-amber-500 shrink-0" />
          ),
          subtitle:
            "Moderate risk factors detected that warrant attention and habit improvements.",
        };
      case "HIGH":
        return {
          badgeText: "HIGH RISK",
          badgeVariant: "destructive" as const,
          containerBg:
            "bg-destructive/10 border-destructive/30 text-destructive dark:text-destructive-foreground",
          progressColor: "bg-destructive",
          icon: (
            <AlertCircleIcon className="w-8 h-8 text-destructive shrink-0" />
          ),
          subtitle:
            "Multiple risk factors or symptoms identified. Timely dental evaluation advised.",
        };
      default:
        return {
          badgeText: "NEUTRAL ASSESSMENT",
          badgeVariant: "outline" as const,
          containerBg: "bg-muted/50 border-border text-foreground",
          progressColor: "bg-primary",
          icon: <InfoIcon className="w-8 h-8 text-primary shrink-0" />,
          subtitle: "Educational assessment summary based on your responses.",
        };
    }
  };

  const riskConfig = getRiskConfig(normalizedLevel);

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in duration-500">
      {/* HEADER TITLE */}
      <div className="text-center space-y-2">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-semibold uppercase tracking-wider">
          <SparklesIcon className="w-3.5 h-3.5" /> AI Diagnostic Summary
        </div>
        <h2 className="text-3xl font-extrabold text-foreground tracking-tight">
          Your AI Oral Health Assessment
        </h2>
        <p className="text-muted-foreground text-sm max-w-xl mx-auto">
          Here is an educational overview generated by AI based on the
          information you provided.
        </p>
      </div>

      {/* OVERALL RISK LEVEL & SCORE CARD */}
      <Card className={`border-2 shadow-xl ${riskConfig.containerBg}`}>
        <CardContent className="p-6 md:p-8 space-y-6">
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div className="flex items-center gap-4">
              {riskConfig.icon}
              <div>
                <div className="flex items-center gap-3">
                  <span className="text-xs uppercase tracking-wider font-semibold text-muted-foreground">
                    Overall Risk Level
                  </span>
                  <Badge
                    variant={riskConfig.badgeVariant}
                    className="px-3 py-0.5 text-xs font-bold uppercase"
                  >
                    {riskConfig.badgeText}
                  </Badge>
                </div>
                <h3 className="text-2xl font-bold mt-1 text-foreground">
                  {normalizedLevel} Risk Profile
                </h3>
                <p className="text-xs md:text-sm text-muted-foreground mt-0.5">
                  {riskConfig.subtitle}
                </p>
              </div>
            </div>

            {/* RISK SCORE GAUGE */}
            <div className="w-full md:w-56 p-4 rounded-xl bg-background/80 backdrop-blur-sm border border-border/60 text-center shrink-0">
              <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Risk Score Indicator
              </div>
              <div className="text-3xl font-black text-foreground mt-1">
                {safeScore}{" "}
                <span className="text-sm font-normal text-muted-foreground">
                  / 100
                </span>
              </div>
              <Progress value={safeScore} className="h-2.5 mt-2 rounded-full" />
            </div>
          </div>

          <p className="text-xs text-muted-foreground border-t border-border/40 pt-3 italic text-center md:text-left">
            ℹ️ Note: This score is an AI-generated educational risk indicator,
            not a clinically validated medical score.
          </p>
        </CardContent>
      </Card>

      {/* RISK FACTORS & RECOMMENDATIONS GRID */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* IDENTIFIED RISK FACTORS */}
        <Card className="border border-border/80 bg-card/90 backdrop-blur-sm shadow-md">
          <CardHeader className="pb-3">
            <CardTitle className="text-lg font-bold flex items-center gap-2 text-foreground">
              <AlertTriangleIcon className="w-5 h-5 text-amber-500" />
              Identified Risk Factors
            </CardTitle>
            <CardDescription className="text-xs">
              Specific concerns identified from your symptoms and habits.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {result.riskFactors && result.riskFactors.length > 0 ? (
              <ul className="space-y-2.5">
                {result.riskFactors.map((factor, idx) => (
                  <li
                    key={idx}
                    className="p-3 rounded-xl bg-muted/40 border border-border/60 text-xs md:text-sm text-foreground flex items-start gap-2.5"
                  >
                    <span className="size-2 rounded-full bg-amber-500 shrink-0 mt-1.5" />
                    <span>{factor}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-xs text-emerald-600 dark:text-emerald-400 flex items-center gap-2">
                <CheckCircle2Icon className="w-4 h-4 shrink-0" />
                <span>
                  No significant risk indicators were identified from your
                  responses.
                </span>
              </div>
            )}
          </CardContent>
        </Card>

        {/* PERSONALIZED RECOMMENDATIONS */}
        <Card className="border border-border/80 bg-card/90 backdrop-blur-sm shadow-md">
          <CardHeader className="pb-3">
            <CardTitle className="text-lg font-bold flex items-center gap-2 text-foreground">
              <ListCheckIcon className="w-5 h-5 text-primary" />
              Personalized Recommendations
            </CardTitle>
            <CardDescription className="text-xs">
              Actionable oral hygiene and lifestyle suggestions.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {result.recommendations && result.recommendations.length > 0 ? (
              <ol className="space-y-2.5">
                {result.recommendations.map((rec, idx) => (
                  <li
                    key={idx}
                    className="p-3 rounded-xl bg-primary/5 border border-primary/10 text-xs md:text-sm text-foreground flex items-start gap-2.5"
                  >
                    <span className="size-5 rounded-full bg-primary/20 text-primary font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                      {idx + 1}
                    </span>
                    <span>{rec}</span>
                  </li>
                ))}
              </ol>
            ) : (
              <p className="text-xs text-muted-foreground p-3 bg-muted/40 rounded-xl">
                Maintain your current daily brushing and flossing routine.
              </p>
            )}
          </CardContent>
        </Card>
      </div>

      {/* WARNING SIGNS SECTION */}
      <Card className="border border-amber-500/30 bg-amber-500/5 backdrop-blur-sm shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-lg font-bold flex items-center gap-2 text-amber-700 dark:text-amber-400">
            <StethoscopeIcon className="w-5 h-5 text-amber-500" />
            Warning Signs & Symptoms to Monitor
          </CardTitle>
          <CardDescription className="text-xs">
            Signs for which professional dental evaluation is recommended.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {result.warningSigns && result.warningSigns.length > 0 ? (
            <ul className="space-y-2">
              {result.warningSigns.map((sign, idx) => (
                <li
                  key={idx}
                  className="p-3 rounded-xl bg-background/80 border border-amber-500/20 text-xs md:text-sm text-foreground flex items-start gap-2.5"
                >
                  <AlertCircleIcon className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
                  <span>{sign}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-muted-foreground p-3 bg-background/80 rounded-xl border border-border/50">
              No specific clinical warning signs were identified from your
              responses.
            </p>
          )}
        </CardContent>
      </Card>

      {/* RECOMMENDED NEXT STEP */}
      {result.nextStep && (
        <Card className="border-2 border-primary/30 bg-gradient-to-r from-primary/10 via-primary/5 to-transparent shadow-lg">
          <CardContent className="p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-primary mb-1">
                Recommended Next Step
              </div>
              <p className="text-base font-semibold text-foreground">
                {result.nextStep}
              </p>
            </div>
            <Button
              asChild
              className="rounded-xl font-semibold bg-primary hover:bg-primary/90 text-white shrink-0 shadow-md"
            >
              <Link href="/appointments">
                Book Appointment <ArrowRightIcon className="w-4 h-4 ml-1" />
              </Link>
            </Button>
          </CardContent>
        </Card>
      )}

      {/* IMPORTANT SAFETY DISCLAIMER */}
      <Card className="border border-border/80 bg-muted/30">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-bold flex items-center gap-2 text-muted-foreground">
            <ShieldAlertIcon className="w-4 h-4 text-muted-foreground" />
            Important Disclaimer
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-xs text-muted-foreground leading-relaxed">
            {result.disclaimer ||
              "This AI-generated assessment is for educational purposes only and does not constitute a dental or medical diagnosis. Please consult a licensed dental professional for a comprehensive clinical evaluation."}
          </p>
        </CardContent>
      </Card>

      {/* ACTION BUTTONS */}
      <div className="flex flex-col sm:flex-row justify-center items-center gap-4 pt-2">
        <Button
          type="button"
          onClick={onReset}
          variant="outline"
          className="w-full sm:w-auto rounded-xl font-semibold border-2 border-primary/20 hover:border-primary/40 px-6 py-2.5"
        >
          <RotateCcwIcon className="w-4 h-4 mr-2" />
          Take Assessment Again
        </Button>

        <Button
          asChild
          className="w-full sm:w-auto rounded-xl font-semibold bg-primary hover:bg-primary/90 text-white px-6 py-2.5 shadow-md"
        >
          <Link href="/dashboard">
            <LayoutDashboardIcon className="w-4 h-4 mr-2" />
            Go to Dashboard
          </Link>
        </Button>
      </div>
    </div>
  );
}
